spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resource
    username: root
    password:

##
#spring:
#  #数据库连接信息
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test_db
#    username: Test_db
#    password: yk3P8PN6KzAHmbay
#  redis:
#    host: 127.0.0.1
#    port: 6379
#





##8.134.176.185
  redis:
    host: 8.134.176.185
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100
  mail:
    properties:
      mail:
        stmp:
        auth: true
        starttls:
          enable: true
          required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
          port: 465
        timeout: 2000
#



#驼峰命名自动
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    # 配置自定义类型处理器
  type-handlers-package: com.utils.StringToArrayTypeHandler
#server:
#  port: 8080
    # 调试开关（用于拦截器）
debug:
  mode:
    enabled: true
